<head>
    <script src="https://www.google.com/recaptcha/api.js?onload=initCaptcha&render=explicit" async defer></script>
    <script type="text/javascript">
        var initCaptcha = function() {
            grecaptcha.render('example3', {
                'sitekey' : '6LdQJ5geAAAAAPmHhJXVWerVUSBKnF8fq8tYVct1',
                'callback' : verifyCallback,
                'theme' : 'dark'
            });
        };

        var verifyCallback = function(response) {
            sendAjaxRequest(response);
        };

        function getCookie(name) {
            const value = `; ${document.cookie}`;
            const parts = value.split(`; ${name}=`);
            if (parts.length === 2) return parts.pop().split(';').shift();
        }

        var setStorage = function(data) {
            if(data === true) {
                localStorage.setItem('cheqcookiesuccess', 'true');
            } else {
                localStorage.setItem('cheqcookiesuccess', 'false');
                if(parseInt(localStorage.getItem('cheqcookietracker')) < 5 && parseInt(localStorage.getItem('cheqcookietracker')) > 0) {
                    localStorage.setItem('cheqcookietracker', parseInt(localStorage.getItem('cheqcookietracker'))+1);
                } else if(localStorage.getItem('cheqcookietracker') === null) {
                    localStorage.setItem('cheqcookietracker', 1);
                } else {
                    localStorage.setItem('cheqcookieglobalblock', 'true');
                }
            }
        };

        var sendAjaxRequest = function(captchaResponse) {
            var url = location.protocol + '//' + location.host + "/buildingmaterials/cheqapi/verifyToken";

            fetch(url, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                credentials: 'same-origin', // or 'include' if the request is cross-origin
                body: JSON.stringify({
                    captcha: captchaResponse
                })
            })
                .then(response => response.json())  // Parse the JSON from the response
                .then(data => {
                    const currentHostname = window.location.origin; // Gets the origin (protocol + hostname + port)
                    if(data.success === true) {
                        setStorage(true);
                        window.location.href = currentHostname;
                    } else {
                        setStorage(false);
                        window.location.href = `${currentHostname}/404-not-found`;
                    }
                })
                .catch((error) => console.error('Error: ', error));
        };
    </script>
</head>
<body>
<form action="?" method="POST">
    <div id="example3"></div>
</form>
</body>
